/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID vesit.ves.ac.in)
#  Generated on:      Fri Apr 10 15:21:59 2026
#  Design:            pwm_gen
#  Command:           saveNetlist project_postroute.v
###############################################################
*/
module pwm_gen (
	clk, 
	reset, 
	duty, 
	pwm_out);
   input clk;
   input reset;
   input [7:0] duty;
   output pwm_out;

   // Internal wires
   wire [7:0] counter;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;

   DFFTRX1M pwm_out_reg (.D(n_34),
	.CK(clk),
	.RN(n_35),
	.Q(pwm_out),
	.QN(UNCONNECTED));
   DFFTRX1M \counter_reg[6]  (.D(n_31),
	.CK(clk),
	.RN(n_35),
	.Q(counter[6]),
	.QN(UNCONNECTED0));
   DFFTRX1M \counter_reg[7]  (.D(n_33),
	.CK(clk),
	.RN(n_35),
	.Q(counter[7]),
	.QN(UNCONNECTED1));
   NAND2XLM g756__2398 (.A(n_35),
	.B(n_30),
	.Y(n_34));
   OAI2BB2XLM g744__5107 (.A0N(counter[7]),
	.A1N(n_32),
	.B0(n_32),
	.B1(counter[7]),
	.Y(n_33));
   INVXLM g745 (.A(n_28),
	.Y(n_31));
   DFFTRX1M \counter_reg[5]  (.D(n_27),
	.CK(clk),
	.RN(n_35),
	.Q(counter[5]),
	.QN(UNCONNECTED2));
   OAI221XLM g759__6260 (.A0(n_24),
	.A1(n_29),
	.B0(n_29),
	.B1(n_8),
	.C0(n_19),
	.Y(n_30));
   OAI21XLM g747__4319 (.A0(n_26),
	.A1(counter[6]),
	.B0(n_32),
	.Y(n_28));
   DFFTRX1M \counter_reg[4]  (.D(n_23),
	.CK(clk),
	.RN(n_35),
	.Q(counter[4]),
	.QN(UNCONNECTED3));
   AOI2BB1XLM g750__8428 (.A0N(n_25),
	.A1N(counter[5]),
	.B0(n_26),
	.Y(n_27));
   NAND2XLM g748__5526 (.A(counter[6]),
	.B(n_26),
	.Y(n_32));
   DFFTRX1M \counter_reg[3]  (.D(n_22),
	.CK(clk),
	.RN(n_35),
	.Q(counter[3]),
	.QN(n_4));
   AND2X1M g751__6783 (.A(n_25),
	.B(counter[5]),
	.Y(n_26));
   OAI221XLM g761__3680 (.A0(counter[4]),
	.A1(n_7),
	.B0(counter[3]),
	.B1(n_0),
	.C0(n_20),
	.Y(n_24));
   AOI2BB1XLM g754__1617 (.A0N(n_21),
	.A1N(counter[4]),
	.B0(n_25),
	.Y(n_23));
   DFFTRX1M \counter_reg[2]  (.D(n_17),
	.CK(clk),
	.RN(n_35),
	.Q(counter[2]),
	.QN(n_1));
   AOI2BB1XLM g758__2802 (.A0N(n_18),
	.A1N(counter[3]),
	.B0(n_21),
	.Y(n_22));
   OAI221XLM g763__1705 (.A0(n_1),
	.A1(duty[2]),
	.B0(n_4),
	.B1(duty[3]),
	.C0(n_16),
	.Y(n_20));
   AND2X1M g755__5122 (.A(n_21),
	.B(counter[4]),
	.Y(n_25));
   DFFTRX1M \counter_reg[1]  (.D(n_13),
	.CK(clk),
	.RN(n_35),
	.Q(counter[1]),
	.QN(UNCONNECTED4));
   OAI21XLM g766__8246 (.A0(n_14),
	.A1(counter[7]),
	.B0(n_15),
	.Y(n_19));
   AND2X1M g760__7098 (.A(n_18),
	.B(counter[3]),
	.Y(n_21));
   AOI2BB1XLM g764__6131 (.A0N(n_11),
	.A1N(counter[2]),
	.B0(n_18),
	.Y(n_17));
   OAI222XLM g767__1881 (.A0(counter[2]),
	.A1(n_3),
	.B0(n_10),
	.B1(n_12),
	.C0(n_9),
	.C1(counter[1]),
	.Y(n_16));
   OAI2BB1XLM g768__5115 (.A0N(counter[7]),
	.A1N(n_14),
	.B0(duty[7]),
	.Y(n_15));
   AOI2BB1XLM g772__7482 (.A0N(n_12),
	.A1N(counter[1]),
	.B0(n_11),
	.Y(n_13));
   OAI222XLM g769__4733 (.A0(counter[6]),
	.A1(n_5),
	.B0(counter[7]),
	.B1(n_2),
	.C0(n_6),
	.C1(counter[5]),
	.Y(n_29));
   AND2X1M g765__6161 (.A(n_11),
	.B(counter[2]),
	.Y(n_18));
   OAI2BB1XLM g770__9315 (.A0N(n_9),
	.A1N(counter[1]),
	.B0(duty[0]),
	.Y(n_10));
   AOI22XLM g773__9945 (.A0(counter[4]),
	.A1(n_7),
	.B0(n_6),
	.B1(counter[5]),
	.Y(n_8));
   DFFTRX1M \counter_reg[0]  (.D(counter[0]),
	.CK(clk),
	.RN(n_35),
	.Q(n_12),
	.QN(counter[0]));
   AND2X1M g774__2883 (.A(counter[6]),
	.B(n_5),
	.Y(n_14));
   AND2X1M g775__2346 (.A(n_12),
	.B(counter[1]),
	.Y(n_11));
   INVXLM g777 (.A(duty[2]),
	.Y(n_3));
   INVXLM g783 (.A(duty[5]),
	.Y(n_6));
   INVXLM g779 (.A(duty[4]),
	.Y(n_7));
   INVXLM g784 (.A(duty[7]),
	.Y(n_2));
   INVXLM g776 (.A(duty[3]),
	.Y(n_0));
   INVXLM g778 (.A(duty[1]),
	.Y(n_9));
   INVXLM g780 (.A(duty[6]),
	.Y(n_5));
   INVXLM g786 (.A(reset),
	.Y(n_35));
endmodule

