
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr  9 2026 13:58:37 IST (Apr  9 2026 08:28:37 UTC)

// Verification Directory fv/pwm_gen 

module pwm_gen(clk, reset, duty, pwm_out);
  input clk, reset;
  input [7:0] duty;
  output pwm_out;
  wire clk, reset;
  wire [7:0] duty;
  wire pwm_out;
  wire [7:0] counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35;
  DFFTRX1 pwm_out_reg(.CK (clk), .D (n_34), .RN (n_35), .Q (pwm_out),
       .QN (UNCONNECTED));
  DFFTRX1 \counter_reg[6] (.CK (clk), .D (n_31), .RN (n_35), .Q
       (counter[6]), .QN (UNCONNECTED0));
  DFFTRX1 \counter_reg[7] (.CK (clk), .D (n_33), .RN (n_35), .Q
       (counter[7]), .QN (UNCONNECTED1));
  NAND2XL g756__2398(.A (n_35), .B (n_30), .Y (n_34));
  OAI2BB2XL g744__5107(.A0N (counter[7]), .A1N (n_32), .B0 (n_32), .B1
       (counter[7]), .Y (n_33));
  INVXL g745(.A (n_28), .Y (n_31));
  DFFTRX1 \counter_reg[5] (.CK (clk), .D (n_27), .RN (n_35), .Q
       (counter[5]), .QN (UNCONNECTED2));
  OAI221XL g759__6260(.A0 (n_24), .A1 (n_29), .B0 (n_29), .B1 (n_8),
       .C0 (n_19), .Y (n_30));
  OAI21XL g747__4319(.A0 (n_26), .A1 (counter[6]), .B0 (n_32), .Y
       (n_28));
  DFFTRX1 \counter_reg[4] (.CK (clk), .D (n_23), .RN (n_35), .Q
       (counter[4]), .QN (UNCONNECTED3));
  AOI2BB1XL g750__8428(.A0N (n_25), .A1N (counter[5]), .B0 (n_26), .Y
       (n_27));
  NAND2XL g748__5526(.A (counter[6]), .B (n_26), .Y (n_32));
  DFFTRX1 \counter_reg[3] (.CK (clk), .D (n_22), .RN (n_35), .Q
       (counter[3]), .QN (n_4));
  AND2X1 g751__6783(.A (n_25), .B (counter[5]), .Y (n_26));
  OAI221XL g761__3680(.A0 (counter[4]), .A1 (n_7), .B0 (counter[3]),
       .B1 (n_0), .C0 (n_20), .Y (n_24));
  AOI2BB1XL g754__1617(.A0N (n_21), .A1N (counter[4]), .B0 (n_25), .Y
       (n_23));
  DFFTRX1 \counter_reg[2] (.CK (clk), .D (n_17), .RN (n_35), .Q
       (counter[2]), .QN (n_1));
  AOI2BB1XL g758__2802(.A0N (n_18), .A1N (counter[3]), .B0 (n_21), .Y
       (n_22));
  OAI221XL g763__1705(.A0 (n_1), .A1 (duty[2]), .B0 (n_4), .B1
       (duty[3]), .C0 (n_16), .Y (n_20));
  AND2X1 g755__5122(.A (n_21), .B (counter[4]), .Y (n_25));
  DFFTRX1 \counter_reg[1] (.CK (clk), .D (n_13), .RN (n_35), .Q
       (counter[1]), .QN (UNCONNECTED4));
  OAI21XL g766__8246(.A0 (n_14), .A1 (counter[7]), .B0 (n_15), .Y
       (n_19));
  AND2X1 g760__7098(.A (n_18), .B (counter[3]), .Y (n_21));
  AOI2BB1XL g764__6131(.A0N (n_11), .A1N (counter[2]), .B0 (n_18), .Y
       (n_17));
  OAI222XL g767__1881(.A0 (counter[2]), .A1 (n_3), .B0 (n_10), .B1
       (n_12), .C0 (n_9), .C1 (counter[1]), .Y (n_16));
  OAI2BB1XL g768__5115(.A0N (counter[7]), .A1N (n_14), .B0 (duty[7]),
       .Y (n_15));
  AOI2BB1XL g772__7482(.A0N (n_12), .A1N (counter[1]), .B0 (n_11), .Y
       (n_13));
  OAI222XL g769__4733(.A0 (counter[6]), .A1 (n_5), .B0 (counter[7]),
       .B1 (n_2), .C0 (n_6), .C1 (counter[5]), .Y (n_29));
  AND2X1 g765__6161(.A (n_11), .B (counter[2]), .Y (n_18));
  OAI2BB1XL g770__9315(.A0N (n_9), .A1N (counter[1]), .B0 (duty[0]), .Y
       (n_10));
  AOI22XL g773__9945(.A0 (counter[4]), .A1 (n_7), .B0 (n_6), .B1
       (counter[5]), .Y (n_8));
  DFFTRX1 \counter_reg[0] (.CK (clk), .D (counter[0]), .RN (n_35), .Q
       (n_12), .QN (counter[0]));
  AND2X1 g774__2883(.A (counter[6]), .B (n_5), .Y (n_14));
  AND2X1 g775__2346(.A (n_12), .B (counter[1]), .Y (n_11));
  INVXL g777(.A (duty[2]), .Y (n_3));
  INVXL g783(.A (duty[5]), .Y (n_6));
  INVXL g779(.A (duty[4]), .Y (n_7));
  INVXL g784(.A (duty[7]), .Y (n_2));
  INVXL g776(.A (duty[3]), .Y (n_0));
  INVXL g778(.A (duty[1]), .Y (n_9));
  INVXL g780(.A (duty[6]), .Y (n_5));
  INVXL g786(.A (reset), .Y (n_35));
endmodule

